title: Econ Ipsum
authors: 
  - matthew:
    name: Matthew Wildrick Thomas
    domain: https://mattwthomas.com
  - maria:
    name: Maria Fernanda Petri Betto
    domain: https://mariabetto.com
tagline: "Economic Lorem Ipsum"
description: > # this means to ignore newlines until "show_excerpts:"
  Econ Ipsum is a Lorem Ipsum generator that uses words from the abstracts of various economic papers.

theme: minima

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
#  social_links:
    # twitter: jekyllrb
    # github:  jekyll
    # rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md

plugins:
 - jekyll-sitemap
 - jekyll-seo-tag

compress_html:
  comments:
    - ["<!-- , -->"]
    - ["/* , */"]

social:
  links:
    - "https://twitter.com/econipsum"
    - "https://github.com/mwt/econ-ipsum"
    - "https://alternativeto.net/software/econ-ipsum/about/"
    - "https://devmesh.intel.com/projects/econ-ipsum"
    - "https://angel.co/projects/1258296-econ-ipsum"

sass:
    style: compressed

# don't overwrite vercel api
exclude:
- api/